### ISSUE TITLE
Not able to clone due to an white space at the end of the folder name

### ISSUE THREAD

**Issue by ManjunathRK1251** [TLE-MEC/Hack-CP-DSA#428]
![Code_BsGNxDLMun](https://user-images.githubusercontent.com/54987128/135745170-d8a4b128-39d9-4d35-80f1-994d863b4b06.png)

**Comment by Artineer9401** [comment]
This is what I am getting after performing restore:
`$ git restore --source=HEAD :/
error: invalid path 'Leetcode/Minimum Ascii Delete Sum /readme.md'
error: invalid path 'Leetcode/Minimum Ascii Delete Sum /solution.java'`

The problem is with Leetcode/Minimum Ascii Delete Sum folder. Extra whitespace at the end of folder name

**Comment by Vishruth-S** [comment]
Thank you for pointing out. Have fixed, please check now
